name: CI-develop-pr

on:
  pull_request:
    branches:
      - 'Develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm ci
        
      - name: Test
        run: npm run test
        
      - name: Build
        run: npm run build

  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.base.ref == 'Develop' &&
      contains(github.event.pull_request.labels.*.name, 'review requested')
    steps:
      - name: Check if PR has enough reviews
        run: |
          approvals=$(curl -s -H "Authorization: token {{ secrets.GITHUBACTIONKEY }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" \
            | jq '[.[] | select(.state == "APPROVED")] | length')
          echo "Approvals: $approvals"
          if [ "$approvals" -ge 3 ]; then
            echo "Approval count is sufficient, proceeding with auto-merge."
            echo "approved=true" >> $GITHUB_ENV
            curl -X POST -H "Authorization: token ${{ secrets.GITHUBACTIONKEY }}" \
              -d '{"labels":["automerge"]}' \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"


          else
            echo "Not enough approvals yet. (needs 3, got $approvals)"
            echo "approved=false" >> $GITHUB_ENV

      - name: Auto-merge on approval
        if: env.approved == 'true'
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBACTIONKEY }}
          MERGE_LABELS: "Review Requested"
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
