name: Develop to main

on:
  push:
    branches:
      - 'Develop'

jobs: 
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create PR from Develop to main
        run: |
          # 이미 Develop -> main PR이 있는지 확인
          EXISTING_PR=$(gh pr list --base main --head Develop --json number -q '.[0].number')

          if [ -z "$EXISTING_PR" ]; then
            # 최근 커밋 메시지 가져오기
            COMMIT_MSG=$(git log -1 --pretty=%B)
            
            # PR 생성
            PR_URL=$(gh pr create --base main --head Develop --title "Develop -> main: $COMMIT_MSG" --body "Develop 브랜치의 변경사항을 main 브랜치로 자동 머지합니다.")
            echo "PR 생성: $PR_URL"
          else
            echo "PR이 이미 존재합니다: #$EXISTING_PR"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}